### PR TITLE
FindBugs fixes

### PR DESCRIPTION
**Pull request by bhamail**

### CODE REVIEW

**Comment by pfirmstone** [comment]
Thanks Dan,

Those array fields are public and mutable, so there's no real benefit to making defensive copies, apart from having less reported bugs.  We can't really make them false positives, because they are bugs.  What we did was make most of those classes Cloneable, so the whole object could be defensively copied.

If we add getter methods, it would be possible to deprecate the fields and later make them private, then the defensive copies would also provide benefit.  Even though we would retain the fields for Serialization / serial form compatibility, so technically they're published, it's still safe.

Ironically I spent a lot of time tracking down race conditions in ServiceDiscoveryManager related to the design of these classes.

What are your thoughts?  Should we add getter methods and deprecate the public fields?

In a similar vein I would have liked to allow Entry's to have final fields, so even though they have public fields, developers could create Entry's that were immutable, to make them easy to reason about.

Regards,

Peter.

**Comment by bhamail** [comment]
Hi Peter,

Ah, great points. I didn’t consider the clone() implementations.

My first inclination is always towards immutability, but I do remember old discussions about “Space Entries” now that you mention it. Urg. 
Do I understand correctly that the end state of the design would require preserving the public fields? If so, I’m not sure of the value of adding accessor methods with deprecated public fields, other than maybe it at least prevents things (exposing innards) from getting worse in the future.
Or, can “Entry” classes really have private fields now? (I’m not sure.) If so, then I’d be willing to add accessors, deprecate public fields, etc to help move towards that end goal.
I’m a total “fan of final fields” everywhere, so if that is also part of the end goal, I lean that way even more.

Either way, I understand why my System.arraycopy stuff adds no value, so happy to chalk that up to “learning” and toss those changes in the bit bucket.

Dan

**Comment by pfirmstone** [comment]
Yes prob back out array copies for public fields for now.

I'd like to talk about Entry's first, then the other classes later.

Quick clarification; no intent to include private fields in Entry's.

Entry's have their own special marshalling spec that's different from serialization.   They can still be serialized like ordinary serializable objects, but when used by a lookup service or javaspace they're not actually serialized, only their public non final non transient fields are marshalled.. Currently Entry's can't contain final fields, but it would be nice if they could, then they could be immutable in object as well as marshalled form.  Most entry's have string fields.  Entry's that have only String or Number fields have a performance advantage due to the implementation of Reggie not using their marshalled form, yes that does mean we could support comparable lookups, if we wanted to.

Arrays are a problem as they remain mutable and while AbstractEntry is now also Cloneable, arrays won't be cloned unless the entry implementation also overrides the clone method.  Arrays do have the benefit of type safety during unmarshalling of fields.

While it would seem like a good idea to use an unmodifiable collection instead of arrays as Entry fields, there is no way to ensure type safety during unmarshalling.

In fact it's bad to have Collection<Type> as return values from remote methods for the same reason.  It breaks type safety during unmarshalling.

So it seems arrays are the least evil in this case.  In other words best practise would be that entry classes that have array fields should override clone.

I think that immutable Entry's wouldn't need to be Cloneable.  In fact we could make an immutable entry spec where only fields that are public and final are marshalled.  It might also be advantageous to further restrict their fields to String and Number types.

Will comment share thoughts on non entry classes and other stuff later as I'm using a phone.

**Comment by pfirmstone** [comment]
Jxr plugin is a nice touch.

**Comment by pfirmstone** [comment]
For classes that aren't Entry's with mutable array fields the arrays should be defensively copied during clone.

In addition, if we deprecate the public mutable fields in non Entry classes now and provide getter methods, it provides a migration path to make those fields private final and immutable.

**Comment by pfirmstone** [comment]
Dan,

I'm going to go ahead and merge this pull request, then back out the array copies.  There's a lot of good work here and I think the rest should be merged.

Cheers,

Peter.

**Pull request merged**
